import "./App.css";
import React from "react";
import { BrowserRouter, Route, Routes } from "react-router-dom";
import ListaPokemon from "./Componentes/ListaPokemon/ListaPokemon";
import DetallePokemon from "./Componentes/DetallePokemon/DetallePokemon";
import Login from "./Componentes/Login/Login";
import SignUp from "./Componentes/SignUp/SignUp";
import AgregarPokemon from "./Componentes/AgregarPokemon/AgregarPokemon";

function App() {
  return (
    <div className="App">
      <React.StrictMode>
        <BrowserRouter>
          <Routes>
            <Route path="/login" element={<Login />}></Route>
            <Route path="/sign-up" element={<SignUp />}></Route>
            <Route path="/" element={<ListaPokemon />}></Route>
            <Route
              path="DetallePokemon/:nombrePokemon"
              element={<DetallePokemon />}
            ></Route>
            <Route path="/agregarPokemon" element={<AgregarPokemon/>}></Route>
          </Routes>
        </BrowserRouter>
      </React.StrictMode>
    </div>
  );
}

export default App;

// const listaPokemon = [
//   {
//     nombre: "Bulbasaur",
//     color: "#74CB48",
//     icono: "../Materiales/bulbasaur.png",
//     id: "#001",
//     tipo: "Grass",
//     tipoDos: "Poison",
//     tipoDosColor: "#A43E9E",
//     weight: "6,9kg",
//     height: "0,7m",
//     movimiento: "Chlorophyll",
//     movimientoDos: "Overgrow",
//     descripcion:
//       "There is a plant seed on its back right from the day this Pokemon is bron. The seed slowly grows larger",
//     hp: "045",
//     atk: "049",
//     def: "049",
//     satk: "065",
//     sdef: "065",
//     spd: "045",
//   },
//   {
//     nombre: "Ivysaur",
//     color: "#74CB48",
//     icono: "../Materiales/bulbasaur.png",
//     id: "#002",
//     tipo: "Grass",
//     tipoDos: "Poison",
//     tipoDosColor: "#A43E9E",
//     weight: "13,0kg",
//     height: "1m",
//     movimiento: "Synthesis",
//     movimientoDos: "Sweet-scent",
//     descripcion:
//       "Supports the weight of the bulb thanks to its strong legs and trunk.",
//     hp: "055",
//     atk: "053",
//     def: "052",
//     satk: "073",
//     sdef: "070",
//     spd: "049",
//   },
//   {
//     nombre: "Venasaur",
//     color: "#74CB48",
//     icono: "../Materiales/bulbasaur.png",
//     id: "#003",
//     tipo: "Grass",
//     tipoDos: "Poison",
//     tipoDosColor: "#A43E9E",
//     weight: "100,0kg",
//     height: "2,0m",
//     movimiento: "Solar-ray",
//     movimientoDos: "Sleeping-pill",
//     descripcion:
//       "The flower on its back releases a delicate aroma. In combat, this aroma has a relaxing aroma.",
//     hp: "075",
//     atk: "059",
//     def: "090",
//     satk: "080",
//     sdef: "075",
//     spd: "069",
//   },
//   {
//     nombre: "Charmander",
//     color: "#F57D31",
//     id: "#004",
//     tipo: "Fire",
//     weight: "8,5kg",
//     height: "0,6m",
//     movimiento: "Mega-Punch",
//     movimientoDos: "Fire-Punch",
//     descripcion:
//       "It has a preference for hot things. When it rains, steam is said to sopaut from the tip of its tail",
//     hp: "039",
//     atk: "052",
//     def: "043",
//     satk: "060",
//     sdef: "050",
//     spd: "065",
//   },
//   {
//     nombre: "Charmeleon",
//     color: "#F57D31",
//     id: "#005",
//     tipo: "Fire",
//     weight: "8,5kg",
//     height: "0,6m",
//     movimiento: "Mega-Punch",
//     movimientoDos: "Fire-Punch",
//     descripcion:
//       "It has a preference for hot things. When it rains, steam is said to sopaut from the tip of its tail",
//     hp: "039",
//     atk: "052",
//     def: "043",
//     satk: "060",
//     sdef: "050",
//     spd: "065",
//   },
//   {
//     nombre: "Charizard",
//     color: "#F57D31",
//     id: "#006",
//     tipo: "Fire",
//     tipoDos: "Flying",
//     tipoDosColor: "#A891EC",
//     weight: "8,5kg",
//     height: "0,6m",
//     movimiento: "Mega-Punch",
//     movimientoDos: "Fire-Punch",
//     descripcion:
//       "It has a preference for hot things. When it rains, steam is said to sopaut from the tip of its tail",
//     hp: "039",
//     atk: "052",
//     def: "043",
//     satk: "060",
//     sdef: "050",
//     spd: "065",
//   },
//   {
//     nombre: "Squirtle",
//     color: "#6493EB",
//     id: "#007",
//     tipo: "Water",
//     weight: "9,0kg",
//     height: "0,5m",
//     movimiento: "Torrent",
//     movimientoDos: "Rain-Dish",
//     descripcion:
//       "When it retracts its long neck into its shell, it squirts out water with vigorus force",
//     hp: "044",
//     atk: "048",
//     def: "065",
//     satk: "050",
//     sdef: "064",
//     spd: "043",
//   },
//   {
//     nombre: "Wartortle",
//     color: "#6493EB",
//     id: "#008",
//     tipo: "Water",
//     weight: "9,0kg",
//     height: "0,5m",
//     movimiento: "Torrent",
//     movimientoDos: "Rain-Dish",
//     descripcion:
//       "When it retracts its long neck into its shell, it squirts out water with vigorus force",
//     hp: "044",
//     atk: "048",
//     def: "065",
//     satk: "050",
//     sdef: "064",
//     spd: "043",
//   },
//   {
//     nombre: "Blastoise",
//     color: "#6493EB",
//     id: "#009",
//     tipo: "Water",
//     weight: "9,0kg",
//     height: "0,5m",
//     movimiento: "Torrent",
//     movimientoDos: "Rain-Dish",
//     descripcion:
//       "When it retracts its long neck into its shell, it squirts out water with vigorus force",
//     hp: "044",
//     atk: "048",
//     def: "065",
//     satk: "050",
//     sdef: "064",
//     spd: "043",
//   },
//   {
//     nombre: "Butterfree",
//     color: "#A7B723",
//     id: "#012",
//     tipo: "Bug",
//     tipoDos: "Flying",
//     tipoDosColor: "#A891EC",
//     weight: "32,0kg",
//     height: "1,1m",
//     movimiento: "Compound",
//     movimientoDos: "Tinted-Lens",
//     descripcion:
//       "In batlle, it flaps its wings at great speed to release highly toxic dust into the air",
//     hp: "060",
//     atk: "045",
//     def: "050",
//     satk: "090",
//     sdef: "080",
//     spd: "070",
//   },
//   {
//     nombre: "Pikachu",
//     color: "#F9CF30",
//     id: "#025",
//     tipo: "Electric",
//     weight: "6,0kg",
//     height: "0,4m",
//     movimiento: "Mega-Punch",
//     movimientoDos: "Pay-Day",
//     descripcion:
//       "Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy",
//     hp: "035",
//     atk: "055",
//     def: "040",
//     satk: "050",
//     sdef: "050",
//     spd: "090",
//   },
//   {
//     nombre: "Gastly",
//     color: "#70559B",
//     id: "#092",
//     tipo: "Ghost",
//     tipoDos: "Dark",
//     tipoDosColor: "#75574C",
//     weight: "0.1kg",
//     height: "1,3m",
//     movimiento: "Levitate",
//     descripcion:
//       "Born from grases, anyone would faint if enguelted by its gaseous body, which contains posion",
//     hp: "030",
//     atk: "035",
//     def: "030",
//     satk: "100",
//     sdef: "035",
//     spd: "080",
//   },
//   {
//     nombre: "Ditto",
//     color: "#AAA67F",
//     id: "#132",
//     tipo: "Normal",
//     weight: "4kg",
//     height: "0,3m",
//     movimiento: "Limber",
//     movimientoDos: "imposter",
//     descripcion:
//       "it can reconstitute its entire cellular structure to change into what it sees",
//     hp: "048",
//     atk: "048",
//     def: "048",
//     satk: "048",
//     sdef: "048",
//     spd: "048",
//   },
//   {
//     nombre: "Mew",
//     color: "#FB5584",
//     id: "#152",
//     tipo: "Psychic",
//     weight: "4kg",
//     height: "0,4m",
//     movimiento: "Synchronize",
//     descripcion:
//       "When viewed through a microscope, this Poekmons short, fien, delicate hair can be seen",
//     hp: "100",
//     atk: "100",
//     def: "100",
//     satk: "100",
//     sdef: "100",
//     spd: "100",
//   },
//   {
//     nombre: "Aron",
//     color: "#B7B9D0",
//     id: "#304",
//     tipo: "Steel",
//     tipoDos: "Rock",
//     tipoDosColor: "#B69E31",
//     weight: "60g",
//     height: "0,4m",
//     movimiento: "Sturdy",
//     movimientoDos: "Rock-Head",
//     descripcion:
//       "it eats iron ore - and sometimes railroad tracks - to build up the steel armor that prostects its body",
//     hp: "050",
//     atk: "070",
//     def: "100",
//     satk: "040",
//     sdef: "040",
//     spd: "030",
//   },
//   {
//     nombre: "Flareon",
//     color: "#F57D31",
//     id: "#136",
//     tipo: "Fire",
//     weight: "8,5kg",
//     height: "0,6m",
//     movimiento: "Mega-Punch",
//     movimientoDos: "Fire-Punch",
//     descripcion:
//       "It has a preference for hot things. When it rains, steam is said to sopaut from the tip of its tail",
//     hp: "039",
//     atk: "052",
//     def: "043",
//     satk: "060",
//     sdef: "050",
//     spd: "065",
//   },
//   {
//     nombre: "Lugia",
//     color: "#FB5584",
//     id: "#249",
//     tipo: "Psychic",
//     tipoDos: "Flying",
//     tipoDosColor: "#A891EC",
//     weight: "4kg",
//     height: "0,4m",
//     movimiento: "Synchronize",
//     descripcion:
//       "When viewed through a microscope, this Poekmons short, fien, delicate hair can be seen",
//     hp: "100",
//     atk: "100",
//     def: "100",
//     satk: "100",
//     sdef: "100",
//     spd: "100",
//   },
//   {
//     nombre: "Vaporeon",
//     color: "#6493EB",
//     id: "#134",
//     tipo: "Water",
//     weight: "9,0kg",
//     height: "0,5m",
//     movimiento: "Torrent",
//     movimientoDos: "Rain-Dish",
//     descripcion:
//       "When it retracts its long neck into its shell, it squirts out water with vigorus force",
//     hp: "044",
//     atk: "048",
//     def: "065",
//     satk: "050",
//     sdef: "064",
//     spd: "043",
//   },
// ];
